inputSet:
  name: Build_spring_config_autorefresh_1683211501326-pr-trigger-input-set
  identifier: Build_spring_config_autorefresh_1683211501326prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_spring_config_autorefresh_1683211501326
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
